### ISSUE TITLE
UTF errors under Ruby 1.9.x

### ISSUE THREAD

**Issue by quantumgardener** [patsplat/plist#15] opened 2013-01-09 05:13 UTC
Using plist when called from Hazel on the mac was causing errors that were fixed by adding these lines to the top of Parser.rb. Apologies for the brief explanation. I've lost the original error message. I found the fix here.  http://stackoverflow.com/questions/13650562/invalid-byte-sequence-in-us-ascii-when-trying-to-start-rails-app-with-phusion-pa

```
if RUBY_VERSION =~ /1.9/
  Encoding.default_external = Encoding::UTF_8
  Encoding.default_internal = Encoding::UTF_8
end
```

**Comment by mattbrictson** [comment] 2017-04-18 03:34
Closing as duplicate of #21

**Closed by mattbrictson** 2017-04-18 03:34 UTC
